# お絵描きクイズのお題データ
topics:
  # 食べ物系（基本〜やや難）
  - main: 親子丼
    aliases:
      - 親子どん
      - おやこどん
      - オヤコドン

  - main: 天ぷら
    aliases:
      - てんぷら
      - 天麩羅
      - テンプラ

  - main: おにぎり
    aliases:
      - お握り
      - オニギリ
      - おむすび
      - お結び

  - main: 苺大福
    aliases:
      - いちごだいふく
      - いちご大福
      - イチゴ大福
      - イチゴダイフク

  - main: たこ焼き
    aliases:
      - たこやき
      - タコヤキ
      - たこ焼
      - 蛸焼き

  - main: かき氷
    aliases:
      - かきごおり
      - カキ氷
      - カキゴオリ
      - 欠き氷

  - main: ドリアン
    aliases:
      - どりあん

  # 動物系（基本〜難）
  - main: だんごむし
    aliases:
      - 団子虫
      - ダンゴムシ

  - main: クジャク
    aliases:
      - 孔雀
      - くじゃく

  - main: マンモス
    aliases:
      - まんもす

  - main: ブルドック
    aliases:
      - ぶるどっく
      - ブルドッグ

  - main: うなぎ
    aliases:
      - 鰻
      - ウナギ

  - main: キリン
    aliases:
      - きりん
      - 麒麟

  - main: ペンギン
    aliases:
      - ぺんぎん

  - main: コウモリ
    aliases:
      - こうもり
      - 蝙蝠

  # 物・道具系（やや難）
  - main: ピアノ
    aliases:
      - ぴあの

  - main: ちりとり
    aliases:
      - 塵取り
      - チリトリ

  - main: 止まり木
    aliases:
      - とまりぎ
      - 止り木
      - トマリギ

  - main: 枕
    aliases:
      - まくら
      - マクラ

  - main: ティッシュ
    aliases:
      - てぃっしゅ
